# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flockApp2', '0002_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlockGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=1000)),
                ('group_id', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=1000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flockApp2.Company')),
            ],
        ),
        migrations.CreateModel(
            name='MobUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(max_length=80)),
                ('number', models.CharField(max_length=20)),
                ('interaction', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digits', models.CharField(max_length=10)),
                ('flock_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flockApp2.FlockGroup')),
            ],
        ),
    ]
